### ISSUE TITLE
장바구니, 주문 Erd 설계

### ISSUE THREAD

**Issue by JY-Dev** [HanriverProject/backend#3]

**Comment by JY-Dev** [comment]
@KangWookOh 고민을 해봤는데 처음에 멤버를 생성할때 장바구니에 대한 Id를 생성(MemberId로 대체해도 상관없을듯?)해주고 장바구니 상품이라는 테이블을 만들어서 장바구니 상품 테이블에 장바구니에 추가한 상품들을 관리하는거죠 그 다음 결제를 하게 되면 장바구니 상품에 있는 상품들을 제거해주고 주문 상품 테이블에 장바구니 상품들을 다시 저장하는 방식은 어떤가요? 아니면 하나의 상품 테이블을 만들고 하나의 상태 컬럼을 두는 것도 지금 상황에서는 나쁘지 않을 것 같다고 생각이듭니다. 하지만 하나의 상품 테이블을 두는건 의미가 모호해질 수 있다는 생각이 들어서 저는 전자가 나은것같은데 둘 중 어떤방식이 더 나을지 의견 달아주시면 감사하겠습니다.

**Comment by KangWookOh** [comment]
전자의 경우가 관리하기 좀 더 편할거같습니다 erdcloud에 추가해주시면 엔티티 만어 둘게요!

**Comment by JY-Dev** [comment]
전자로 설계했습니다.
